trigger:
- main

pool:
  name: 'SelfHosted'

steps:
- checkout: self
  submodules: true 

- script: |
    echo "Listing files in the working directory:"
    dir $(Build.SourcesDirectory)  # Lists files in the source directory
  displayName: 'List files in source directory'


- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)/Devops/happytails/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DskipTests'
